default_stages: [commit]
repos:
    - repo: https://github.com/ambv/black
      rev: 24.4.2
      hooks:
      - id: black
        language_version: python3.10
    -  repo: https://github.com/PyCQA/flake8
       rev: 7.1.0
       hooks:
       - id: flake8
    - repo: local
      hooks:
      - id: pytest-check
        types: [python]
        name: pytest
        entry: ./test.sh
        language: python
        pass_filenames: false
        always_run: true